### PR TITLE
Add Simplified Chinese

### PR DESCRIPTION
**Pull request by Chiloven945**

### CODE REVIEW

**Review by KosmoMoustache — CHANGES_REQUESTED** [review]
Can you add yourself to the contributors in fabric.mod.json, thanks I will merge after that

**Comment by Chiloven945** [comment]
Surely

**Review by KosmoMoustache — APPROVED** [review]

**Comment by KosmoMoustache** [comment]
Hey I'm sorry to bothering you, I've made some changes to the translations, would you mind to update your translation before I publish the new version?

The new translations are here: [https://github.com/KosmoMoustache/MusicNotification/tree/next/src/main/resources/assets/musicnotification/lang](https://github.com/KosmoMoustache/MusicNotification/tree/next/src/main/resources/assets/musicnotification/lang)

**Comment by Chiloven945** [comment]
i'll do it asap

**Pull request merged**
